### ISSUE TITLE
Unable to play any other game except sonic

### ISSUE THREAD

**Issue by parik309** [red-prig/fpPS4#140]
Hi,

Thanks a ton for developing this emulator.
I have setup everything and am able to play sonic with xlinput gamepad but I am not able to play any other game.
When I try to play "Adveenture Time : Pirates of the Enchiridion" i get following error

![image](https://github.com/red-prig/fpPS4/assets/69530633/ac5f49d8-c0ec-4082-8241-5e04655ae811)

Any help would be great.

Thanks

**Comment by Addy2004** [comment]
The emulator hasn't been mature enough to support more games like this one. From the error, it seems like it a memory leak or crash. Issues like this will be fixed with the kernel rewriteup which is a WIP as of now. You should try all the playable games if you actually wish to run or play them in the [compatibility-repo](https://github.com/red-prig/fpps4-game-compatibility/issues?q=label%3Astatus-playable). Also join the discord for more help and support. Avoid creating issues here. Github issues are only intended for technical faults.

**Comment by red-prig** [comment]
Read carefully before creating issues (Added details for special people)
