### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by BigSmart69696969** [red-prig/fpPS4#17]
Not a big issue, but no controller support is really making some games hard to play.

**Comment by BigSmart69696969** [comment]
Xpadder is a temporary solution and is costs money.

**Comment by red-prig** [comment]
![9b162cf185aa682e35fcdc6fcbb5cbb6](https://user-images.githubusercontent.com/68122101/176956606-7e19fd0a-17fe-4986-8ad4-3b963e42fed8.jpg)

**Comment by and468860** [comment]
for now iso free program Xpadder has another one does the same joytokey or antimicro

**Comment by jvhellraiser** [comment]
Use AntiMicroX is free and it works for me...

**Comment by GeorgeSpiggott** [comment]
I've attempted to use JoytoKey but for some reason it only works when another app is open and selected. In my case Notepad solves the problem. I'm using the pre-built draft30062022 release.

**Comment by GeorgeSpiggott** [comment]
Resolved my issue. JoytoKey has to be Run as an Administrator to affect fpPS4.

**Comment by jvhellraiser** [comment]
I really need the button layout on the keyboard to config joytokey or AntimicroX anyone knows?

**Comment by GeorgeSpiggott** [comment]
Scroll down here: https://github.com/red-prig/fpPS4

**Comment by jvhellraiser** [comment]
> Scroll down here: https://github.com/red-prig/fpPS4
Thanks but i wanted to say that for me these :
![image_2022-12-14_213704280](https://user-images.githubusercontent.com/16488761/207752043-69d616e9-700d-467b-b599-fe900e8ac946.png)

are not my buttons they act like a D-PAD, i am pretty sure Sonic Jumps in the game but none of the buttons add to the number pad are X,Square,triangle or Circle since i get look up ,look down, walk forward and back, also i am pretty sure the PlayStation controller has a select button.

**Comment by GeorgeSpiggott** [comment]
PS4 controller has 'Options' and 'Share' instead of 'Start' and 'Select'. I mapped 'Options' to 'Menu' (Start) on my Xbox One controller and 'Windows + Up Arrow' (to maximise the window) to the 'Change View' (Select) button. fpPS4 doesn't support the 'Share' button AFAIK.
