### ISSUE TITLE
inet_ntop

### ISSUE THREAD

**Issue by zemzema** [red-prig/fpPS4#173]
Maybe something like this.

unit ps4_libinet;

{$mode ObjFPC}{$H+}

interface

uses
  ctypes;

function ps4_inet_ntop(AF: LongInt; src: Pointer; dst: PChar; size: SizeUInt): PChar; SysV_ABI_CDecl;

implementation

function ps4_inet_ntop(AF: LongInt; src: Pointer; dst: PChar; size: SizeUInt): PChar; SysV_ABI_CDecl;
var
  addr: sockaddr_storage;
  addrSize: socklen_t;
begin
  Result := nil;

  FillChar(addr, SizeOf(addr), 0);

  if AF = AF_INET then
  begin
    addrSize := SizeOf(TInAddr);
    PInAddr(@addr)^ := PInAddr(src)^;
  end
  else if AF = AF_INET6 then
  begin
    addrSize := SizeOf(TIPv6Address);
    PIPv6Address(@addr)^ := PIPv6Address(src)^;
  end
  else
    Exit(nil);

  if inet_ntop(AF, @addr, dst, size) <> nil then
    Result := dst;
end;

end.

**Comment by kr1spy2115** [comment]
ChatGPT's code wont work (xd)

The error that u trynna fix wants to call `inet_ntop` function in `libScePosix` library which doesn't exists but can be made. 

The code is completely wrong and please don't code anything with like ChatGPT or Google Bard since its barebone AI which can barely code simple stuff or atleast learn how to use it. If u really wanna contribute then u can join to our discord server and read contributor's tutorial/requirements.

**Comment by kr1spy2115** [comment]
Also if u could, close this issue and join our discord server for further help, advice or answers for some questions https://discord.gg/up9qatpX7M

**Comment by red-prig** [comment]
some kind of crap

**Comment by red-prig** [comment]
https://github.com/red-prig/fpPS4/commit/373a2e019a56a285307ce8e8fbe94f44509ae70c
